spring.application.name=backend
# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tourmatch_db
spring.datasource.username=postgres
# Reemplaza 'TU_CONTRASEÑA' por la clave que definiste al instalar PostgreSQL
spring.datasource.password=1k3mdoojwK!

# Configuración de JPA / Hibernate
# 'update' permite que Spring Boot cree automáticamente las tablas en pgAdmin
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola para depuración
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret.key=EstaEsUnaLlaveSuperSecretaParaTourMatch2026!

# Puerto en el que correrá tu servidor Backend
server.port=8080